CREATE TABLE IF NOT EXISTS jobs (
      id              INTEGER PRIMARY KEY AUTOINCREMENT,
      name            TEXT NOT NULL UNIQUE,
      url             TEXT NOT NULL,
      frequency_hours REAL NOT NULL DEFAULT 4,
      enabled         INTEGER NOT NULL DEFAULT 1,
      config          TEXT NOT NULL DEFAULT '{}',
      created_at      TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at      TEXT NOT NULL DEFAULT (datetime('now'))
    );
INSERT INTO jobs VALUES(1,'festoolrecon','https://festoolrecon.com',4.0,1,'{"selectors":{"product":"[data-section-type=\"product\"]","name":"[data-section-type=\"product\"] h1","price":".product-single__price-product-template"}}','2026-02-16 20:27:27','2026-02-17 01:41:46','scrape');
CREATE TABLE IF NOT EXISTS runs (
      id              INTEGER PRIMARY KEY AUTOINCREMENT,
      job_id          INTEGER NOT NULL REFERENCES jobs(id),
      started_at      TEXT NOT NULL DEFAULT (datetime('now')),
      completed_at    TEXT,
      status          TEXT NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending', 'running', 'success', 'failed')),
      output_file     TEXT,
      screenshot_file TEXT,
      error_message   TEXT,
      products_found  INTEGER DEFAULT 0
    );
INSERT INTO runs VALUES(1,1,'2026-02-16 20:27:27','2026-02-16 20:27:32','success',NULL,'341d0a02f9781b3359c7f6e707dfd63b522e4f19cc5c3eef042e8528e486d590',NULL,1);
INSERT INTO runs VALUES(2,1,'2026-02-16 20:28:47','2026-02-16 20:28:52','success',NULL,'341d0a02f9781b3359c7f6e707dfd63b522e4f19cc5c3eef042e8528e486d590',NULL,1);
INSERT INTO runs VALUES(3,1,'2026-02-16 20:34:09','2026-02-16 20:34:32','success',NULL,'dd96bb8ba85c7defded029fbb7b08c470a70b2257c854fada392dfb11ec62d89',NULL,1);
INSERT INTO runs VALUES(4,1,'2026-02-17 01:41:46','2026-02-17 01:41:52','success',NULL,'341d0a02f9781b3359c7f6e707dfd63b522e4f19cc5c3eef042e8528e486d590',NULL,1);
CREATE TABLE IF NOT EXISTS files (
      id            INTEGER PRIMARY KEY AUTOINCREMENT,
      hash          TEXT NOT NULL UNIQUE,
      original_name TEXT NOT NULL,
      mime_type     TEXT NOT NULL,
      size_bytes    INTEGER NOT NULL,
      created_at    TEXT NOT NULL DEFAULT (datetime('now'))
    );
INSERT INTO files VALUES(1,'341d0a02f9781b3359c7f6e707dfd63b522e4f19cc5c3eef042e8528e486d590','festoolrecon-2026-02-16T20-27-27.png','image/png',286263,'2026-02-16 20:27:32');
INSERT INTO files VALUES(3,'dd96bb8ba85c7defded029fbb7b08c470a70b2257c854fada392dfb11ec62d89','festoolrecon-2026-02-16T20-34-09.png','image/png',316907,'2026-02-16 20:34:32');
CREATE TABLE IF NOT EXISTS results (
      id         INTEGER PRIMARY KEY AUTOINCREMENT,
      run_id     INTEGER NOT NULL REFERENCES runs(id),
      data       TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
INSERT INTO results VALUES(1,1,'{"totalProducts":1,"products":[{"productName":"Track Saw TSV 60 KEB-F-Plus","msrp":"$1,059.00","discountedPrice":"$847.20","description":"Since 1980, Festool tracksaws have been known for their reliable quality and absolute precision. Our objective: The perfect cut. With the TSV 60 K plunge-cut saw with scoring blade, we have achieved exactly that. Splinter-free cuts on both sides now from the very first cut. Coupled with the built-in KickbackStop, which stops the blade in the blink of an eye not only protects your workpiece but also helps to minimize the risk of injury to your hands. Get the most from the saw with the ideal combination of Festool system accessories, your work can always be precise and customized to your standards, in the shop or on the jobsite. With the TSV 60 K, workshop-quality results can be replicated on the jobsite – as good as with a stationary machine.\n\n\n\nSplinter-free: The scoring blades ensures splinter-free cuts on both sides from the very first cut\nLong-lasting: Diamond scoring saw blade with very long service life for perfect cut quality time after time\nSaw system: comprehensive system with ","features":["Splinter-free: The scoring blades ensures splinter-free cuts on both sides from the very first cut","Long-lasting: Diamond scoring saw blade with very long service life for perfect cut quality time after time","Saw system: comprehensive system with ideal accessories for perfect panel cutting","Peace-of-mind: the unique KickbackStop helps to reduce the risk of injury caused by kickback during sawing or plunge-cutting into the workpiece","Versatile: 2-3/8\" (60 mm) cutting depth and can be combined with the FSK cross cutting guide rail or FS guide rail","Perfect bevels: scoring blade matches the angle even on bevel cuts from 0° to 45°","Flexible: Both the scoring saw blade and the main saw blade can be manually activated and deactivated","Convenient: The FastFix spindle stop on the main saw blade and the possibility of standing it on its side make changing the saw blade very simple, even with the scoring saw blade","Constant: EC-TEC motor in combination with the thin kerf saw blades ensures constant and consistent power for perfect cuts"],"whatsIncluded":["allen key 4","hex key 5mm","scoring saw blade DIA 47x2.5x6.35 T1","sight window","Wood Fine Cut HW 168x1.8x20 WD42 circular saw blade","In SYS3 M437"],"sku":null,"scrapedAt":"2026-02-16T20:27:32.145Z"}],"scrapedAt":"2026-02-16T20:27:32.145Z","source":"https://festoolrecon.com"}','2026-02-16 20:27:32');
INSERT INTO results VALUES(2,2,'{"totalProducts":1,"products":[{"productName":"Track Saw TSV 60 KEB-F-Plus","msrp":"$1,059.00","discountedPrice":"$847.20","description":"Since 1980, Festool tracksaws have been known for their reliable quality and absolute precision. Our objective: The perfect cut. With the TSV 60 K plunge-cut saw with scoring blade, we have achieved exactly that. Splinter-free cuts on both sides now from the very first cut. Coupled with the built-in KickbackStop, which stops the blade in the blink of an eye not only protects your workpiece but also helps to minimize the risk of injury to your hands. Get the most from the saw with the ideal combination of Festool system accessories, your work can always be precise and customized to your standards, in the shop or on the jobsite. With the TSV 60 K, workshop-quality results can be replicated on the jobsite – as good as with a stationary machine.\n\n\n\nSplinter-free: The scoring blades ensures splinter-free cuts on both sides from the very first cut\nLong-lasting: Diamond scoring saw blade with very long service life for perfect cut quality time after time\nSaw system: comprehensive system with ","features":["Splinter-free: The scoring blades ensures splinter-free cuts on both sides from the very first cut","Long-lasting: Diamond scoring saw blade with very long service life for perfect cut quality time after time","Saw system: comprehensive system with ideal accessories for perfect panel cutting","Peace-of-mind: the unique KickbackStop helps to reduce the risk of injury caused by kickback during sawing or plunge-cutting into the workpiece","Versatile: 2-3/8\" (60 mm) cutting depth and can be combined with the FSK cross cutting guide rail or FS guide rail","Perfect bevels: scoring blade matches the angle even on bevel cuts from 0° to 45°","Flexible: Both the scoring saw blade and the main saw blade can be manually activated and deactivated","Convenient: The FastFix spindle stop on the main saw blade and the possibility of standing it on its side make changing the saw blade very simple, even with the scoring saw blade","Constant: EC-TEC motor in combination with the thin kerf saw blades ensures constant and consistent power for perfect cuts"],"whatsIncluded":["allen key 4","hex key 5mm","scoring saw blade DIA 47x2.5x6.35 T1","sight window","Wood Fine Cut HW 168x1.8x20 WD42 circular saw blade","In SYS3 M437"],"sku":null,"scrapedAt":"2026-02-16T20:28:52.212Z"}],"scrapedAt":"2026-02-16T20:28:52.212Z","source":"https://festoolrecon.com"}','2026-02-16 20:28:52');
INSERT INTO results VALUES(3,3,'{"totalProducts":1,"products":[{"productName":"Track Saw TSV 60 KEB-F-Plus","msrp":"$1,059.00","discountedPrice":"$847.20","description":"Since 1980, Festool tracksaws have been known for their reliable quality and absolute precision. Our objective: The perfect cut. With the TSV 60 K plunge-cut saw with scoring blade, we have achieved exactly that. Splinter-free cuts on both sides now from the very first cut. Coupled with the built-in KickbackStop, which stops the blade in the blink of an eye not only protects your workpiece but also helps to minimize the risk of injury to your hands. Get the most from the saw with the ideal combination of Festool system accessories, your work can always be precise and customized to your standards, in the shop or on the jobsite. With the TSV 60 K, workshop-quality results can be replicated on the jobsite – as good as with a stationary machine.\n\n\n\nSplinter-free: The scoring blades ensures splinter-free cuts on both sides from the very first cut\nLong-lasting: Diamond scoring saw blade with very long service life for perfect cut quality time after time\nSaw system: comprehensive system with ","features":["Splinter-free: The scoring blades ensures splinter-free cuts on both sides from the very first cut","Long-lasting: Diamond scoring saw blade with very long service life for perfect cut quality time after time","Saw system: comprehensive system with ideal accessories for perfect panel cutting","Peace-of-mind: the unique KickbackStop helps to reduce the risk of injury caused by kickback during sawing or plunge-cutting into the workpiece","Versatile: 2-3/8\" (60 mm) cutting depth and can be combined with the FSK cross cutting guide rail or FS guide rail","Perfect bevels: scoring blade matches the angle even on bevel cuts from 0° to 45°","Flexible: Both the scoring saw blade and the main saw blade can be manually activated and deactivated","Convenient: The FastFix spindle stop on the main saw blade and the possibility of standing it on its side make changing the saw blade very simple, even with the scoring saw blade","Constant: EC-TEC motor in combination with the thin kerf saw blades ensures constant and consistent power for perfect cuts"],"whatsIncluded":["allen key 4","hex key 5mm","scoring saw blade DIA 47x2.5x6.35 T1","sight window","Wood Fine Cut HW 168x1.8x20 WD42 circular saw blade","In SYS3 M437"],"sku":null,"scrapedAt":"2026-02-16T20:34:32.117Z"}],"scrapedAt":"2026-02-16T20:34:32.117Z","source":"https://festoolrecon.com"}','2026-02-16 20:34:32');
INSERT INTO results VALUES(4,4,'{"totalProducts":1,"products":[{"productName":"Track Saw TSV 60 KEB-F-Plus","msrp":"$1,059.00","discountedPrice":"$847.20","description":"Since 1980, Festool tracksaws have been known for their reliable quality and absolute precision. Our objective: The perfect cut. With the TSV 60 K plunge-cut saw with scoring blade, we have achieved exactly that. Splinter-free cuts on both sides now from the very first cut. Coupled with the built-in KickbackStop, which stops the blade in the blink of an eye not only protects your workpiece but also helps to minimize the risk of injury to your hands. Get the most from the saw with the ideal combination of Festool system accessories, your work can always be precise and customized to your standards, in the shop or on the jobsite. With the TSV 60 K, workshop-quality results can be replicated on the jobsite – as good as with a stationary machine.\n\n\n\nSplinter-free: The scoring blades ensures splinter-free cuts on both sides from the very first cut\nLong-lasting: Diamond scoring saw blade with very long service life for perfect cut quality time after time\nSaw system: comprehensive system with ","features":["Splinter-free: The scoring blades ensures splinter-free cuts on both sides from the very first cut","Long-lasting: Diamond scoring saw blade with very long service life for perfect cut quality time after time","Saw system: comprehensive system with ideal accessories for perfect panel cutting","Peace-of-mind: the unique KickbackStop helps to reduce the risk of injury caused by kickback during sawing or plunge-cutting into the workpiece","Versatile: 2-3/8\" (60 mm) cutting depth and can be combined with the FSK cross cutting guide rail or FS guide rail","Perfect bevels: scoring blade matches the angle even on bevel cuts from 0° to 45°","Flexible: Both the scoring saw blade and the main saw blade can be manually activated and deactivated","Convenient: The FastFix spindle stop on the main saw blade and the possibility of standing it on its side make changing the saw blade very simple, even with the scoring saw blade","Constant: EC-TEC motor in combination with the thin kerf saw blades ensures constant and consistent power for perfect cuts"],"whatsIncluded":["allen key 4","hex key 5mm","scoring saw blade DIA 47x2.5x6.35 T1","sight window","Wood Fine Cut HW 168x1.8x20 WD42 circular saw blade","In SYS3 M437"],"sku":null,"scrapedAt":"2026-02-17T01:41:52.078Z"}],"scrapedAt":"2026-02-17T01:41:52.078Z","source":"https://festoolrecon.com"}','2026-02-17 01:41:52');
CREATE INDEX IF NOT EXISTS idx_runs_job_id ON runs(job_id);
CREATE INDEX IF NOT EXISTS idx_runs_status ON runs(status);
CREATE INDEX IF NOT EXISTS idx_runs_job_started ON runs(job_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_files_hash ON files(hash);
CREATE INDEX IF NOT EXISTS idx_results_run_id ON results(run_id);
